### ISSUE TITLE
digits in heatmap_fst()

### ISSUE THREAD

**Issue by siberianhigh** [thierrygosselin/assigner#17] opened 2020-01-07 12:32 UTC
Nothing happens when I'm trying to change argument 'digits' in heatmap_fst(), it is always 5 decimal digits on heatmap. For instance:

heatmap_fst(fst.ci$pairwise.fst.full.matrix, fst.ci$pairwise.fst.ci.matrix, n.s = TRUE,
            digits = 3, color.low = "white", color.mid = "grey",
            color.high = "black", text.size = 4, plot.size = 40,
            pop.levels = NULL, path.folder = NULL, filename = NULL)

heatmap_fst(fst.ci$pairwise.fst.full.matrix, fst.ci$pairwise.fst.ci.matrix, n.s = TRUE,
            digits = 5, color.low = "white", color.mid = "grey",
            color.high = "black", text.size = 4, plot.size = 40,
            pop.levels = NULL, path.folder = NULL, filename = NULL)

heatmap_fst(fst.ci$pairwise.fst.full.matrix, fst.ci$pairwise.fst.ci.matrix, n.s = TRUE,
            digits = 8, color.low = "white", color.mid = "grey",
            color.high = "black", text.size = 4, plot.size = 40,
            pop.levels = NULL, path.folder = NULL, filename = NULL)

all three give me identical results.

There is another problem, probably related to the described above - the fst values and corresponding CI intervals are mixed between upper and lower parts of matrix on the heatmap:

Warning messages:
1: Column `POP1` has different attributes on LHS and RHS of join 
2: Column `POP2` has different attributes on LHS and RHS of join 

![plot](https://user-images.githubusercontent.com/47352273/71895505-08fcb280-3173-11ea-95ba-f79a1c782043.png)

> devtools::session_info()
─ Session info 
 setting  value                       
 version  R version 3.6.2 (2019-12-12)
 os       Ubuntu 18.04.3 LTS          
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Asia/Yekaterinburg          
 date     2020-01-07                  

─ Packages 
 package          * version   date       lib source                                   
 ade4             * 1.7-13    2018-08-31 [1] CRAN (R 3.6.1)                           
 adegenet         * 2.1.1     2018-02-02 [1] CRAN (R 3.6.1)                           
 ape                5.3       2019-03-17 [1] CRAN (R 3.6.1)                           
 assertthat         0.2.1     2019-03-21 [1] CRAN (R 3.6.1)                           
 assigner         * 0.5.6     2019-12-08 [1] Github (thierrygosselin/assigner@b941111)
 backports          1.1.5     2019-10-02 [1] CRAN (R 3.6.1)                           
 Biobase            2.44.0    2019-05-02 [1] Bioconductor                             
 BiocGenerics       0.30.0    2019-05-02 [1] Bioconductor                             
 Biostrings         2.52.0    2019-05-02 [1] Bioconductor                             
 bitops             1.0-6     2013-08-17 [1] CRAN (R 3.6.1)                           
 boot               1.3-24    2019-12-20 [4] CRAN (R 3.6.2)                           
 broom              0.5.2     2019-04-07 [1] CRAN (R 3.6.1)                           
 callr              3.3.2     2019-09-22 [1] CRAN (R 3.6.1)                           
 class              7.3-15    2019-01-01 [4] CRAN (R 3.6.1)                           
 classInt           0.4-2     2019-10-17 [1] CRAN (R 3.6.1)                           
 cli                1.1.0     2019-03-19 [1] CRAN (R 3.6.1)                           
 cluster            2.1.0     2019-06-19 [4] CRAN (R 3.6.1)                           
 coda               0.19-3    2019-07-05 [1] CRAN (R 3.6.1)                           
 colorspace         1.4-1     2019-03-18 [1] CRAN (R 3.6.1)                           
 crayon             1.3.4     2017-09-16 [1] CRAN (R 3.6.1)                           
 data.table         1.12.6    2019-10-18 [1] CRAN (R 3.6.1)                           
 DBI                1.0.0     2018-05-02 [1] CRAN (R 3.6.1)                           
 deldir             0.1-23    2019-07-31 [1] CRAN (R 3.6.1)                           
 desc               1.2.0     2018-05-01 [1] CRAN (R 3.6.1)                           
 devtools           2.1.0     2019-07-06 [1] CRAN (R 3.6.1)                           
 digest             0.6.23    2019-11-23 [1] CRAN (R 3.6.1)                           
 dplyr              0.8.3     2019-07-04 [1] CRAN (R 3.6.1)                           
 e1071              1.7-3     2019-11-26 [1] CRAN (R 3.6.1)                           
 ellipsis           0.3.0     2019-09-20 [1] CRAN (R 3.6.1)                           
 expm               0.999-4   2019-03-21 [1] CRAN (R 3.6.1)                           
 fansi              0.4.0     2018-10-05 [1] CRAN (R 3.6.1)                           
 farver             2.0.1     2019-11-13 [1] CRAN (R 3.6.1)                           
 fastmap            1.0.1     2019-10-08 [1] CRAN (R 3.6.1)                           
 fs                 1.3.1     2019-05-06 [1] CRAN (R 3.6.1)                           
 fst                0.9.0     2019-04-09 [1] CRAN (R 3.6.1)                           
 gdata              2.18.0    2017-06-06 [1] CRAN (R 3.6.1)                           
 gdsfmt             1.20.0    2019-05-02 [1] Bioconductor                             
 generics           0.0.2     2018-11-29 [1] CRAN (R 3.6.1)                           
 GenomeInfoDb       1.20.0    2019-05-02 [1] Bioconductor                             
 GenomeInfoDbData   1.2.1     2019-12-08 [1] Bioconductor                             
 GenomicRanges      1.36.1    2019-09-06 [1] Bioconductor                             
 ggplot2            3.2.1     2019-08-10 [1] CRAN (R 3.6.1)                           
 glue               1.3.1     2019-03-12 [1] CRAN (R 3.6.1)                           
 gmodels            2.18.1    2018-06-25 [1] CRAN (R 3.6.1)                           
 gridExtra          2.3       2017-09-09 [1] CRAN (R 3.6.1)                           
 gtable             0.3.0     2019-03-25 [1] CRAN (R 3.6.1)                           
 gtools             3.8.1     2018-06-26 [1] CRAN (R 3.6.1)                           
 GWASExactHW        1.01      2013-01-05 [1] CRAN (R 3.6.1)                           
 hms                0.5.2     2019-10-30 [1] CRAN (R 3.6.1)                           
 htmltools          0.4.0     2019-10-04 [1] CRAN (R 3.6.1)                           
 httpuv             1.5.2     2019-09-11 [1] CRAN (R 3.6.1)                           
 igraph             1.2.4.2   2019-11-27 [1] CRAN (R 3.6.1)                           
 IRanges            2.18.3    2019-09-24 [1] Bioconductor                             
 jomo               2.6-10    2019-10-22 [1] CRAN (R 3.6.1)                           
 KernSmooth         2.23-16   2019-10-15 [4] CRAN (R 3.6.1)                           
 labeling           0.3       2014-08-23 [1] CRAN (R 3.6.1)                           
 later              1.0.0     2019-10-04 [1] CRAN (R 3.6.1)                           
 lattice            0.20-38   2018-11-04 [4] CRAN (R 3.6.1)                           
 lazyeval           0.2.2     2019-03-15 [1] CRAN (R 3.6.1)                           
 LearnBayes         2.15.1    2018-03-18 [1] CRAN (R 3.6.1)                           
 lifecycle          0.1.0     2019-08-01 [1] CRAN (R 3.6.1)                           
 lme4               1.1-21    2019-03-05 [1] CRAN (R 3.6.1)                           
 logistf            1.23      2018-07-19 [1] CRAN (R 3.6.1)                           
 magrittr           1.5       2014-11-22 [1] CRAN (R 3.6.1)                           
 MASS               7.3-51.5  2019-12-20 [4] CRAN (R 3.6.2)                           
 Matrix             1.2-18    2019-11-27 [4] CRAN (R 3.6.1)                           
 memoise            1.1.0     2017-04-21 [1] CRAN (R 3.6.1)                           
 mgcv               1.8-31    2019-11-09 [4] CRAN (R 3.6.1)                           
 mice               3.6.0     2019-07-10 [1] CRAN (R 3.6.1)                           
 mime               0.7       2019-06-11 [1] CRAN (R 3.6.1)                           
 minqa              1.2.4     2014-10-09 [1] CRAN (R 3.6.1)                           
 mitml              0.3-7     2019-01-07 [1] CRAN (R 3.6.1)                           
 munsell            0.5.0     2018-06-12 [1] CRAN (R 3.6.1)                           
 nlme               3.1-143   2019-12-10 [4] CRAN (R 3.6.2)                           
 nloptr             1.2.1     2018-10-03 [1] CRAN (R 3.6.1)                           
 nnet               7.3-12    2016-02-02 [4] CRAN (R 3.6.1)                           
 pan                1.6       2018-06-29 [1] CRAN (R 3.6.1)                           
 pbmcapply          1.5.0     2019-07-10 [1] CRAN (R 3.6.1)                           
 permute            0.9-5     2019-03-12 [1] CRAN (R 3.6.1)                           
 pillar             1.4.2     2019-06-29 [1] CRAN (R 3.6.1)                           
 pinfsc50           1.1.0     2016-12-02 [1] CRAN (R 3.6.1)                           
 pkgbuild           1.0.5     2019-08-26 [1] CRAN (R 3.6.1)                           
 pkgconfig          2.0.3     2019-09-22 [1] CRAN (R 3.6.1)                           
 pkgload            1.0.2     2018-10-29 [1] CRAN (R 3.6.1)                           
 plyr               1.8.4     2016-06-08 [1] CRAN (R 3.6.1)                           
 prettyunits        1.0.2     2015-07-13 [1] CRAN (R 3.6.1)                           
 processx           3.4.1     2019-07-18 [1] CRAN (R 3.6.1)                           
 promises           1.1.0     2019-10-04 [1] CRAN (R 3.6.1)                           
 ps                 1.3.0     2018-12-21 [1] CRAN (R 3.6.1)                           
 purrr              0.3.3     2019-10-18 [1] CRAN (R 3.6.1)                           
 R6                 2.4.1     2019-11-12 [1] CRAN (R 3.6.1)                           
 radiator         * 1.1.2     2019-12-08 [1] Github (thierrygosselin/radiator@480ef0f)
 Rcpp               1.0.3     2019-11-08 [1] CRAN (R 3.6.1)                           
 RCurl              1.95-4.12 2019-03-04 [1] CRAN (R 3.6.1)                           
 readr              1.3.1     2018-12-21 [1] CRAN (R 3.6.1)                           
 remotes            2.1.0     2019-06-24 [1] CRAN (R 3.6.1)                           
 reshape2           1.4.3     2017-12-11 [1] CRAN (R 3.6.1)                           
 rlang              0.4.2     2019-11-23 [1] CRAN (R 3.6.1)                           
 rpart              4.1-15    2019-04-12 [4] CRAN (R 3.6.1)                           
 rprojroot          1.3-2     2018-01-03 [1] CRAN (R 3.6.1)                           
 rstudioapi         0.10      2019-03-19 [1] CRAN (R 3.6.1)                           
 S4Vectors          0.22.1    2019-09-09 [1] Bioconductor                             
 scales             1.1.0     2019-11-18 [1] CRAN (R 3.6.1)                           
 SeqArray           1.24.2    2019-07-12 [1] Bioconductor                             
 seqinr             3.6-1     2019-09-07 [1] CRAN (R 3.6.1)                           
 SeqVarTools        1.22.0    2019-05-02 [1] Bioconductor                             
 sessioninfo        1.1.1     2018-11-05 [1] CRAN (R 3.6.1)                           
 sf                 0.8-0     2019-09-17 [1] CRAN (R 3.6.1)                           
 shiny              1.4.0     2019-10-10 [1] CRAN (R 3.6.1)                           
 sp                 1.3-2     2019-11-07 [1] CRAN (R 3.6.1)                           
 spData             0.3.2     2019-09-19 [1] CRAN (R 3.6.1)                           
 spdep              1.1-3     2019-09-18 [1] CRAN (R 3.6.1)                           
 stringi            1.4.3     2019-03-12 [1] CRAN (R 3.6.1)                           
 stringr            1.4.0     2019-02-10 [1] CRAN (R 3.6.1)                           
 survival           3.1-8     2019-12-03 [4] CRAN (R 3.6.2)                           
 testthat           2.2.1     2019-07-25 [1] CRAN (R 3.6.1)                           
 tibble             2.1.3     2019-06-06 [1] CRAN (R 3.6.1)                           
 tidyr              1.0.0     2019-09-11 [1] CRAN (R 3.6.1)                           
 tidyselect         0.2.5     2018-10-11 [1] CRAN (R 3.6.1)                           
 units              0.6-5     2019-10-08 [1] CRAN (R 3.6.1)                           
 UpSetR             1.4.0     2019-05-22 [1] CRAN (R 3.6.1)                           
 usethis            1.5.1     2019-07-04 [1] CRAN (R 3.6.1)                           
 utf8               1.1.4     2018-05-24 [1] CRAN (R 3.6.1)                           
 vcfR             * 1.8.0     2018-04-17 [1] CRAN (R 3.6.1)                           
 vctrs              0.2.0     2019-07-05 [1] CRAN (R 3.6.1)                           
 vegan              2.5-6     2019-09-01 [1] CRAN (R 3.6.1)                           
 viridisLite        0.3.0     2018-02-01 [1] CRAN (R 3.6.1)                           
 withr              2.1.2     2018-03-15 [1] CRAN (R 3.6.1)                           
 xtable             1.8-4     2019-04-21 [1] CRAN (R 3.6.1)                           
 XVector            0.24.0    2019-05-02 [1] Bioconductor                             
 zeallot            0.1.0     2018-01-28 [1] CRAN (R 3.6.1)                           
 zlibbioc           1.30.0    2019-05-02 [1] Bioconductor

**Comment by thierrygosselin** [comment] 2020-01-08 16:20
That's not normal. thanks for highlighting the bug, will have a look at it today.

**Comment by siberianhigh** [comment] 2020-01-09 13:37
Great, I ready to provide data files used, if necessary. But I got these problems with different vcf/metadata combinations.

**Comment by thierrygosselin** [comment] 2020-01-22 01:46
**problem 1: digits**

solved.
it was fixed internally

**problem 2: Fst and CI mixed up**

This was caused by `pop.levels = NULL`.
When this argument is supplied a string, it works
Now when `NULL` the info is taken from the Fst data file/object column names.
Documentation was updated.

Remember that you can generate the heatmap as you do the Fst using `...` argument.

Cheers
and thanks for highlighting the bug

v. 0.5.7 fixes the problems

**Closed as completed by thierrygosselin** 2020-01-22 01:46 UTC
